/* eslint-disable @typescript-eslint/no-require-imports -- Test the actual mobile editing model without native runtime. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript')
const loaded={exports:{}}
new Function('exports',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../../addmin-app/src/lib/portable-text.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(loaded.exports)
const api=loaded.exports
const block=()=>({_type:'block',_key:'paragraph',style:'h2',markDefs:[{_key:'link1',_type:'link',href:'https://example.com'}],children:[{_type:'span',_key:'a',text:'Prvi ',marks:['strong'],future:'keep'},{_type:'span',_key:'b',text:'drugi',marks:['link1','em']}],custom:'keep'})
test('unchanged Portable Text keeps all fields, keys and annotations',()=>{const b=block();assert.equal(api.replaceBlockText(b,api.blockText(b)),b);assert.equal(api.blockText(b),'Prvi drugi')})
test('editing a substring retains unrelated formatting and document metadata',()=>{const b=block(),next=api.replaceBlockText(b,'Prvi novi drugi');assert.equal(api.blockText(next),'Prvi novi drugi');assert.equal(next.custom,'keep');assert.deepEqual(next.markDefs,b.markDefs);assert.deepEqual(next.children.at(-1),b.children[1]);assert.deepEqual(b,block());assert.equal(new Set(next.children.map(s=>s._key)).size,next.children.length)})
test('selected words alone get bold, and applying again removes it',()=>{const b=block(),marked=api.markSelection(b,6,9,'strong');assert.equal(api.blockText(marked),'Prvi drugi');assert.ok(marked.children.some(s=>s.text==='rug'&&s.marks.includes('strong')));const removed=api.markSelection(marked,6,9,'strong');assert.ok(removed.children.some(s=>s.text==='rug'&&!s.marks.includes('strong')));assert.deepEqual(removed.children[0],b.children[0])})
test('links are applied and removed only for the chosen range',()=>{const b=block(),linked=api.markSelection(b,0,4,'new-link',{_type:'link',href:'https://example.com/new'});assert.equal(linked.markDefs.length,2);const removed=api.removeLinks(linked,0,4);assert.ok(!removed.children[0].marks.includes('new-link'));assert.ok(removed.children.at(-1).marks.includes('link1'))})
test('unknown blocks, inline objects and annotations are protected, never flattened',()=>{for(const b of [{...block(),_type:'futureBlock'},{...block(),children:[{_type:'futureInline',_key:'f'}]},{...block(),markDefs:[{_type:'custom',_key:'f'}]},{...block(),children:[{_type:'span',_key:'a',text:'x',marks:['unknown']}]}]){assert.equal(api.editableBlock(b),false);assert.equal(api.replaceBlockText(b,'destructive'),b);assert.equal(api.markSelection(b,0,1,'strong'),b)}})
test('empty paragraph and deletion remain valid keyed Portable Text',()=>{const empty=api.newBlock();assert.equal(api.editableBlock(empty),true);const deleted=api.replaceBlockText(block(),'');assert.equal(deleted.children.length,1);assert.equal(deleted.children[0].text,'');assert.ok(deleted.children[0]._key)})
